pull_request_rules:
  - name: Add label to feature branches
    conditions:
      - base~=(?i)^(feat|feature).*
    actions:
      label:
        add: [feature]
  - name: Add label to bugfix branches
    conditions:
      - base~=(?i)^(fix|bugfix).*
    actions:
      label:
        add: [bug]
  - name: Add label to scala-steward PRs
    conditions:
      - author=usommerl
      - title~=(?i)Update
      - body~=(?i)Configure Scala Steward for your repository
    actions:
      label:
        add: [dependency-update]
  - name: Automatically merge Scala Steward PRs on CI success
    conditions:
      - author=usommerl
      - title~=(?i)Update
      - body~=(?i)Configure Scala Steward for your repository
      - status-success=ci
    actions:
      merge:
        method: merge
  - name: Automatically merge Dependabot PRs on CI success
    conditions:
      - author=dependabot[bot]
      - status-success=ci
    actions:
      merge:
        method: merge
  - name: Delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:
