name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Enhancements'
    when:
      label: 'enhancement'
  - title: 'Bug fixes'
    when:
      labels:
        - 'fix'
        - 'bugfix'
        - 'bug'
  - title: 'Dependency updates'
    when:
      label: 'dependency-update'
change-template: '- $TITLE: #$NUMBER by @$AUTHOR'
template: |
  $CHANGES
